import { useEffect, useState } from 'react'
import { Activity, ArrowLeft, ArrowRight, Check, ChevronDown, CircleDollarSign, Eye, EyeOff, KeyRound, Loader2, LogOut, Plus, RefreshCw, Save, Search, ShieldCheck, SlidersHorizontal, Trash2, Users, X, Zap } from 'lucide-react'
import { Credentials, FeeRate, PageMeta, Trader, getDefaultFee, getPublicAccount, getUserFeePage, getVolumePage, setFee } from './api'

type Rule = { id: string; min: number; maker: number; taker: number; rwaMaker: number; rwaTaker: number }
type Row = Trader & { volume: number; tier: number; current: FourFees; target: FourFees; selected: boolean; changed: boolean }
type FourFees = { maker: number; taker: number; rwaMaker: number; rwaTaker: number }
const LOGIN_KEY='orderly-fee-manager.credentials', CONFIG_KEY='orderly-fee-manager.config'
const colors=['#eaf8df','#e5f2ff','#f4eaff','#fff1db','#e9efeb']
const defaults:Rule[]=[
  {id:crypto.randomUUID(),min:10_000_000,maker:.018,taker:.045,rwaMaker:.018,rwaTaker:.045},
  {id:crypto.randomUUID(),min:1_000_000,maker:.020,taker:.050,rwaMaker:.020,rwaTaker:.050},
  {id:crypto.randomUUID(),min:100_000,maker:.022,taker:.055,rwaMaker:.022,rwaTaker:.055},
]
const iso=(d:Date)=>d.toISOString().slice(0,10), today=iso(new Date()), ago=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n);return iso(d)}
const money=new Intl.NumberFormat('en-US',{maximumFractionDigits:0}), short=(s:string)=>s?`${s.slice(0,6)}...${s.slice(-4)}`:'—', pct=(n:number)=>(n*100).toFixed(3)
const rate6=(n:number)=>Math.round(n*1_000_000)/1_000_000, percent4=(n:number)=>rate6(n/100)*100
const same=(a:FourFees,b:FourFees)=>Math.abs(a.maker-b.maker)<1e-9&&Math.abs(a.taker-b.taker)<1e-9&&Math.abs(a.rwaMaker-b.rwaMaker)<1e-9&&Math.abs(a.rwaTaker-b.rwaTaker)<1e-9

export default function App(){
  const [credentials,setCredentials]=useState<Credentials|null>(()=>{try{return JSON.parse(localStorage.getItem(LOGIN_KEY)||'null')}catch{return null}})
  const [verified,setVerified]=useState(false),[defaultFee,setDefaultFee]=useState<FeeRate|null>(null),[busy,setBusy]=useState(false)
  const [notice,setNotice]=useState<{type:'ok'|'error';text:string}|null>(null),[progress,setProgress]=useState('')
  const [rules,setRules]=useState<Rule[]>(defaults),[brokerId,setBrokerId]=useState(''),[startDate,setStartDate]=useState(ago(29)),[endDate,setEndDate]=useState(today)
  const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[meta,setMeta]=useState<PageMeta>({total:0,current_page:1,records_per_page:25})
  const [rows,setRows]=useState<Row[]>([]),[onlyChanges,setOnlyChanges]=useState(false),[lastRefresh,setLastRefresh]=useState('')

  useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(CONFIG_KEY)||'null');if(s){setRules((s.rules||defaults).map((r:Rule)=>({...r,rwaMaker:r.rwaMaker??r.maker,rwaTaker:r.rwaTaker??r.taker})));setBrokerId(s.brokerId||'');setStartDate(s.startDate||ago(29));setEndDate(s.endDate||today);setPageSize(s.pageSize||25)}}catch{}},[])
  useEffect(()=>{if(credentials&&!verified)verify(credentials)},[])

  async function verify(c:Credentials,remember=true){setBusy(true);setNotice(null);try{const [fee,account]=await Promise.all([getDefaultFee(c),getPublicAccount(c.environment,c.accountId)]);setCredentials(c);setDefaultFee(fee);setBrokerId(account.broker_id);setVerified(true);remember?localStorage.setItem(LOGIN_KEY,JSON.stringify(c)):localStorage.removeItem(LOGIN_KEY);setNotice({type:'ok',text:`Admin verified · ${account.broker_id}`})}catch(e){setVerified(false);setNotice({type:'error',text:e instanceof Error?e.message:'Verification failed'})}finally{setBusy(false)}}
  function saveConfig(){localStorage.setItem(CONFIG_KEY,JSON.stringify({rules,brokerId,startDate,endDate,pageSize}));setNotice({type:'ok',text:'Configuration saved in this browser'})}
  function defaultFour():FourFees{return{maker:defaultFee?.maker_fee_rate||0,taker:defaultFee?.taker_fee_rate||0,rwaMaker:defaultFee?.rwa_maker_fee_rate??defaultFee?.maker_fee_rate??0,rwaTaker:defaultFee?.rwa_taker_fee_rate??defaultFee?.taker_fee_rate??0}}
  function target(volume:number){const sorted=[...rules].sort((a,b)=>b.min-a.min),tier=sorted.findIndex(r=>volume>=r.min);if(tier<0)return{fees:defaultFour(),tier:rules.length};const r=sorted[tier];return{fees:{maker:rate6(r.maker/100),taker:rate6(r.taker/100),rwaMaker:rate6(r.rwaMaker/100),rwaTaker:rate6(r.rwaTaker/100)},tier}}
  function makeRow(u:Trader,volumes:Map<string,number>):Row{const volume=volumes.get(u.address.trim().toLowerCase())||0,t=target(volume),current={maker:Number(u.maker_fee_rate??defaultFour().maker),taker:Number(u.taker_fee_rate??defaultFour().taker),rwaMaker:Number(u.rwa_maker_fee_rate??defaultFour().rwaMaker),rwaTaker:Number(u.rwa_taker_fee_rate??defaultFour().rwaTaker)},changed=!same(current,t.fees);return{...u,volume,tier:t.tier,current,target:t.fees,changed,selected:changed}}
  function validate(){if(!credentials||!brokerId.trim())throw new Error('Broker ID is required');if(new Date(endDate)<new Date(startDate))throw new Error('End date must be after start date');if((+new Date(endDate)-+new Date(startDate))/864e5>90)throw new Error('Date range cannot exceed 90 days')}

  async function fetchVolumeMap(all=false){if(!credentials)return new Map<string,number>();const map=new Map<string,number>();let p=1,total=1;do{setProgress(all?`Loading address volume page ${p}…`:'Loading address volumes…');const data=await getVolumePage(credentials,brokerId.trim(),startDate,endDate,p,500);data.rows.forEach(r=>{const address=r.address?.trim().toLowerCase();if(address)map.set(address,Number(r.perp_volume||0))});total=data.meta.total;p++}while(all&&(p-1)*500<total);return map}
  async function refresh(next=page){setBusy(true);setNotice(null);try{validate();setProgress('Loading accounts…');const [accounts,volumes]=await Promise.all([getUserFeePage(credentials!,next,pageSize),fetchVolumeMap(true)]);setRows(accounts.rows.map(u=>makeRow(u,volumes)));setMeta(accounts.meta);setPage(next);setLastRefresh(new Date().toLocaleTimeString());setNotice({type:'ok',text:`Page ${next} refreshed · ${accounts.meta.total} accounts total`})}catch(e){setNotice({type:'error',text:e instanceof Error?e.message:'Refresh failed'})}finally{setBusy(false);setProgress('')}}
  async function autoScan(){setBusy(true);setNotice(null);try{validate();const volumes=await fetchVolumeMap(true),all:Row[]=[];let p=1,total=1;do{setProgress(`Scanning account page ${p}…`);const data=await getUserFeePage(credentials!,p,500);all.push(...data.rows.map(u=>makeRow(u,volumes)));total=data.meta.total;p++}while((p-1)*500<total);const changes=all.filter(r=>r.changed);setRows(changes);setMeta({total:changes.length,current_page:1,records_per_page:changes.length||1});setPage(1);setOnlyChanges(true);setLastRefresh(new Date().toLocaleTimeString());setNotice({type:'ok',text:`Auto scan complete · ${changes.length} of ${all.length} accounts need modification`})}catch(e){setNotice({type:'error',text:e instanceof Error?e.message:'Auto scan failed'})}finally{setBusy(false);setProgress('')}}
  async function saveChanges(){const selected=rows.filter(r=>r.selected);if(!credentials||!selected.length)return;setBusy(true);try{const groups=new Map<string,Row[]>();selected.forEach(r=>{const k=Object.values(r.target).join('|');groups.set(k,[...(groups.get(k)||[]),r])});let n=0;for(const group of groups.values())for(let i=0;i<group.length;i+=500){if(n++)await new Promise(r=>setTimeout(r,1050));const f=group[0].target;await setFee(credentials,group.slice(i,i+500).map(r=>r.account_id),{maker_fee_rate:f.maker,taker_fee_rate:f.taker,rwa_maker_fee_rate:f.rwaMaker,rwa_taker_fee_rate:f.rwaTaker})}setRows(rs=>rs.map(r=>r.selected?{...r,current:r.target,changed:false,selected:false}:r));setNotice({type:'ok',text:`Updated all four fee rates for ${selected.length} accounts`})}catch(e){setNotice({type:'error',text:e instanceof Error?e.message:'Save failed'})}finally{setBusy(false)}}
  function edit(row:number,key:keyof FourFees,value:number){setRows(rs=>rs.map((r,i)=>i===row?{...r,target:{...r.target,[key]:rate6(value/100)},changed:true,selected:true}:r))}
  function logout(){localStorage.removeItem(LOGIN_KEY);setCredentials(null);setVerified(false);setRows([])}
  if(!credentials||!verified)return <Login initial={credentials} busy={busy} notice={notice} onLogin={verify} onForget={()=>{localStorage.removeItem(LOGIN_KEY);setCredentials(null);setNotice(null)}}/>
  const visible=onlyChanges?rows.filter(r=>r.changed):rows, changed=rows.filter(r=>r.changed).length, selected=rows.filter(r=>r.selected).length, pages=Math.max(1,Math.ceil(meta.total/pageSize))
  return <div className="app-shell"><header><div className="brand"><div className="logo"><Activity size={20}/></div><span>Orderly</span><b>Fee Manager</b></div><div className="header-right"><span className="network"><i/> {credentials.environment==='mainnet'?'Mainnet':'Testnet'}</span><span className="account"><ShieldCheck size={16}/> Admin · {short(credentials.accountId)}</span><button className="icon-btn" onClick={logout}><LogOut size={18}/></button></div></header><main>
    <section className="hero"><div><p className="eyebrow">BROKER OPERATIONS</p><h1>VIP Fee Management</h1><p>Paginated account review with automatic four-rate tier scanning.</p></div><div className="hero-stat"><span>Builder default</span><strong>{pct(defaultFour().maker)}% <small>Maker</small></strong><strong>{pct(defaultFour().taker)}% <small>Taker</small></strong><strong>{pct(defaultFour().rwaMaker)}% <small>RWA Maker</small></strong><strong>{pct(defaultFour().rwaTaker)}% <small>RWA Taker</small></strong></div></section>
    {notice&&<div className={`toast ${notice.type}`}><span>{notice.type==='ok'?<Check size={16}/>:<X size={16}/>} {notice.text}</span><button onClick={()=>setNotice(null)}><X size={14}/></button></div>}
    <div className="layout wide-config"><aside className="panel config-panel"><div className="panel-title"><div><SlidersHorizontal size={18}/><span>Fee tiers</span></div><button className="text-btn" onClick={saveConfig}><Save size={15}/> Save config</button></div><p className="muted">Inputs are percentages: 0.15 means 0.15% and is sent as 0.0015. Values snap to 0.000001 API-rate increments (0.0001% here).</p>
      <div className="rule-head four"><span>VOLUME ≥</span><span>MAKER</span><span>TAKER</span><span>RWA Maker</span><span>RWA Taker</span><span/></div>{[...rules].sort((a,b)=>b.min-a.min).map((r,idx)=><div className="rule-row four" key={r.id} style={{borderLeft:`4px solid ${colors[idx%colors.length]}`}}><div className="money-input"><b>$</b><input type="number" value={r.min} onChange={e=>setRules(x=>x.map(y=>y.id===r.id?{...y,min:+e.target.value}:y))}/></div>{(['maker','taker','rwaMaker','rwaTaker'] as const).map(k=><div className="percent-input" key={k}><input type="number" min="0" step=".0001" value={r[k]} onChange={e=>setRules(x=>x.map(y=>y.id===r.id?{...y,[k]:percent4(+e.target.value)}:y))}/><b>%</b></div>)}<button className="delete" onClick={()=>setRules(x=>x.filter(y=>y.id!==r.id))}><Trash2 size={15}/></button></div>)}<button className="add-rule" onClick={()=>setRules(x=>[...x,{id:crypto.randomUUID(),min:0,maker:0,taker:0,rwaMaker:0,rwaTaker:0}])}><Plus size={16}/> Add tier</button></aside>
      <section className="panel scan-panel"><div className="panel-title"><div><Search size={18}/><span>Account source</span></div>{lastRefresh&&<small>Updated {lastRefresh}</small>}</div><div className="form-grid"><label>Broker ID<input value={brokerId} onChange={e=>setBrokerId(e.target.value)}/></label><label>Rows per page<div className="select-wrap"><select value={pageSize} onChange={e=>{setPageSize(+e.target.value);setPage(1)}}><option>10</option><option>25</option><option>50</option><option>100</option></select><ChevronDown size={15}/></div></label><label>Volume from<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>Volume to<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div><div className="scan-stack"><button className="secondary" disabled={busy} onClick={()=>refresh(page)}><RefreshCw className={busy?'spin':''} size={17}/> Refresh current page</button><button className="primary" disabled={busy} onClick={autoScan}>{busy?<Loader2 className="spin" size={17}/>:<Zap size={17}/>} Auto scan all accounts</button></div>{progress&&<p className="progress"><Loader2 className="spin" size={13}/>{progress}</p>}</section></div>
    <section className="panel results"><div className="results-head"><div><div className="panel-title bare"><div><CircleDollarSign size={19}/><span>All accounts</span><em>{meta.total} total</em>{changed>0&&<em>{changed} changes</em>}</div></div><p className="muted">Background color shows the matched volume tier. Edit any target rate before saving.</p></div><div className="result-actions"><label className="filter-check"><input type="checkbox" checked={onlyChanges} onChange={e=>setOnlyChanges(e.target.checked)}/> Needs modification only</label><button className="secondary" disabled={!changed} onClick={()=>setRows(x=>x.map(r=>({...r,selected:r.changed})))}>Select changes</button><button className="primary" disabled={!selected||busy} onClick={saveChanges}><Save size={17}/> Save {selected||''}</button></div></div>
      {!rows.length?<div className="empty"><div><Users size={26}/></div><h3>Load the account list</h3><p>Refresh a page for review, or run Auto scan to find every account that needs modification.</p></div>:<div className="table-wrap"><table className="fee-table"><thead><tr><th><input type="checkbox" checked={selected>0&&selected===changed} onChange={e=>setRows(x=>x.map(r=>({...r,selected:r.changed&&e.target.checked})))}/></th><th>ACCOUNT</th><th>VOLUME</th><th>CURRENT (Maker / Taker / RWA Maker / RWA Taker)</th><th>TARGET MAKER</th><th>TARGET TAKER</th><th>TARGET RWA MAKER</th><th>TARGET RWA TAKER</th><th>STATUS</th></tr></thead><tbody>{visible.map((r,i)=><tr key={r.account_id} style={{background:colors[r.tier%colors.length]}}><td><input type="checkbox" disabled={!r.changed} checked={r.selected} onChange={e=>setRows(x=>x.map(y=>y.account_id===r.account_id?{...y,selected:e.target.checked}:y))}/></td><td><b>{short(r.address)}</b><small>{short(r.account_id)}</small></td><td><strong>${money.format(r.volume)}</strong><small>Tier {r.tier<rules.length?r.tier+1:'Default'}</small></td><td className="current-four"><span>{pct(r.current.maker)} / {pct(r.current.taker)} / {pct(r.current.rwaMaker)} / {pct(r.current.rwaTaker)}%</span></td>{(['maker','taker','rwaMaker','rwaTaker'] as const).map(k=><td key={k}><RateInput value={r.target[k]} onChange={v=>edit(rows.findIndex(x=>x.account_id===r.account_id),k,v)}/></td>)}<td>{r.changed?<em className="pill">Change</em>:<em className="pill matched">Matched</em>}</td></tr>)}</tbody></table></div>}
      <div className="pagination"><span>Page {page} of {pages}</span><div><button disabled={busy||page<=1} onClick={()=>refresh(page-1)}><ArrowLeft size={15}/> Previous</button><button disabled={busy||page>=pages} onClick={()=>refresh(page+1)}>Next <ArrowRight size={15}/></button></div></div>
    </section></main></div>
}

function RateInput({value,onChange}:{value:number;onChange:(n:number)=>void}){return <div className="table-input"><input type="number" min="0" step=".0001" value={(value*100).toFixed(4)} onChange={e=>onChange(percent4(+e.target.value))}/><b>%</b></div>}
function Login({initial,busy,notice,onLogin,onForget}:{initial:Credentials|null;busy:boolean;notice:{type:'ok'|'error';text:string}|null;onLogin:(c:Credentials,r?:boolean)=>void;onForget:()=>void}){const[a,setA]=useState(initial?.accountId||''),[k,setK]=useState(initial?.privateKey||''),[env,setEnv]=useState<'mainnet'|'testnet'>(initial?.environment||'mainnet'),[show,setShow]=useState(false),[remember,setRemember]=useState(true);return <div className="login-page"><div className="login-bg"><div/><div/><div/></div><section className="login-card"><div className="login-brand"><div className="logo"><Activity size={22}/></div><span>Orderly</span></div><p className="eyebrow">BROKER OPERATIONS</p><h1>VIP Fee Manager</h1><p className="login-sub">Volume-based fee management for every broker account.</p>{notice&&<div className={`login-alert ${notice.type}`}>{notice.type==='error'?<X size={16}/>:<Check size={16}/>}<span>{notice.text}</span></div>}<form onSubmit={e=>{e.preventDefault();onLogin({accountId:a,privateKey:k,environment:env},remember)}}><label>Environment<div className="segmented"><button type="button" className={env==='mainnet'?'active':''} onClick={()=>setEnv('mainnet')}><i/> Mainnet</button><button type="button" className={env==='testnet'?'active':''} onClick={()=>setEnv('testnet')}>Testnet</button></div></label><label>Orderly Account ID<div className="login-input"><ShieldCheck size={18}/><input required value={a} onChange={e=>setA(e.target.value)} placeholder="0x..."/></div></label><label>Orderly Private Key<div className="login-input"><KeyRound size={18}/><input required type={show?'text':'password'} value={k} onChange={e=>setK(e.target.value)} placeholder="32-byte hex or base58"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><label className="remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Save login in this browser</label><button className="login-submit" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<ShieldCheck size={18}/>} Verify admin & continue</button></form>{initial&&<button className="forget" onClick={onForget}>Forget saved login</button>}<div className="security-note"><ShieldCheck size={18}/><p><b>Local-only credentials</b><br/>Credentials stay in this browser's localStorage. Do not save them on a shared device.</p></div></section><footer>Powered by Orderly Network · Admin access only</footer></div>}
